server:
  port: 443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: hochoafree_com.p12
    key-store-password: hochoafree
    key-alias: hochoafree
spring:
  application:
    name: hoc-hoa-free
  datasource:
    url: jdbc:mysql://hoc-hoa-free.cmtyz3ymyhr2.ap-southeast-1.rds.amazonaws.com:3306/hoc_hoa_free
    username: admin
    password: binhcaong
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 10
  servlet:
    multipart:
      maxFileSize: 30MB

uploadFile:
  usingS3: true
  endpointUrl: https://hoc-hoa-free.s3.ap-southeast-1.amazonaws.com
  accessKey: AKIAV4YK64JNKKTB75FD
  secretKey: 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
  bucketName: hoc-hoa-free
