server.port: 8000 
spring:
  application:
    name: hoc-hoa-free
  datasource:
    url: jdbc:mysql://hoc-hoa-free.cmtyz3ymyhr2.ap-southeast-1.rds.amazonaws.com:3306/hoc_hoa_free
    username: admin
    password: binhcaong
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  servlet:
    multipart:
      max-file-size: 30MB
