spring:
  application:
    name: hoc-hoa-free
  datasource:
    url: jdbc:mysql://localhost:3306/hoc_hoa_free
    username: root
    password: binhcaong
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  servlet:
    multipart:
      max-file-size: 30MB
